CBL-4824: Move fixes for 3.1.2 from `next/3.1` to `release/3.1`
couchbase/fleece pull request #187
Opened 2023-08-16 12:31 UTC by callumbirks

Looks like Core release branch requires Fleece submodule points to matching release branch.
This is merged from master up to the point required for CBL-4824, which is the Xcode 14.3 fixes that allow Core to build.

2023-08-16 21:52 UTC, borrrden requested changes
There are beryllium tickets in the commits here, I think those will need to be changed.

2023-08-24 16:44 UTC, velicuvlad commented
[ea80355](https://github.com/couchbase/fleece/pull/187/commits/ea80355fa41036d50f1b13c438b56363faf7115b) has to be taken out. We moved to 11 and 10.14 for 3.1 as well

2023-08-25 13:07 UTC, callumbirks commented
Yeah I think I did this the wrong way. Going to redo

2023-08-25 17:51 UTC, callumbirks commented
Okay so redid this with a cherry-pick of just CBL-4471 ([8e10e3d](https://github.com/couchbase/fleece/commits/8e10e3d0243a1204d2bda589ea13f93404b0c6d2)) which is the only commit in Fleece which needs to brought forward for the 3.1.2 fixes that were sat in the next branch

2023-08-25 18:29 UTC, jianminzhao commented on Xcode/xcconfigs/FleeceTest.xcconfig
>  // Workaround for Catch 2 requiring C++ features not available until macOS 10.12
Is the comment still valid?

2023-08-26 00:11 UTC, borrrden approved these changes

2023-08-29 11:28 UTC, callumbirks commented on Xcode/xcconfigs/FleeceTest.xcconfig
>  // Workaround for Catch 2 requiring C++ features not available until macOS 10.12
Probably not, no. I can remove it

2023-08-29 12:49 UTC, merged