Add a separate property, isCacheable, to SharedKeys.
couchbase/fleece pull request #195
Opened 2023-11-18 00:40 UTC by jianminzhao

If cacheable, Dict::get(key &keyToFind) will cache the string key to integer key and enhance the performance of the ensuing gets. This is good if the doucment is not changed.

For PersistentSharedKey, the library manages the property: it is cacheable only if it is not in a transaction when Dict::get is called.

For SharedKeys, the client manages it. If it anticipates the sharedKeys may outlive the underlying document changes, it should call SharedKeys::disableCaching().

2023-12-04 20:27 UTC, snej requested changes
`LITECORE_CPPTEST` isn't an accurate name because this isn't the LiteCore project. How about `FLEECE_TEST`?

2023-12-04 23:33 UTC, jianminzhao commented
The reason of LITECORE_CPPTEST is because the automatic tests are run from LiteCore. The cmake project of CppTests lumps all tests from fleece with the LiteCore's tests.

2023-12-09 01:12 UTC, jianminzhao commented on Tests/ValueTests.cc
> +        // OutOfRange exception should not contain the backtrace.
This is a mistake. Should be "... not contain the backtrace."

2023-12-11 17:31 UTC, snej approved these changes

2023-12-11 18:09 UTC, merged