CBL-5438: DateTime standard format parser
couchbase/fleece pull request #213
Opened 2024-03-11 14:21 UTC by callumbirks

A proper parser for DateTime formats, rather than just parsing format string as a DateTime.
This has benefits such as additional flexibility in future, but also allows us to keep consistent with the strange "almost-ISO" date format we shipped with CBL-3.1, because keeping format as a `DateTime` does not allow us to optionally use colon or no-colon for Timezone offset (i.e. `+0500` / `+05:00`).
I added in parsing for a "subset" of https://howardhinnant.github.io/date/date.html#to_stream_formatting, but it's not necessary and if anyone thinks we don't need it, happy to take it out. Think it's a lot better than the weird "1111-11-11T11:11......` format we copied from Server though.

2024-03-11 14:31 UTC, callumbirks commented
See Core PR https://github.com/couchbase/couchbase-lite-core/pull/1977

2024-03-11 16:37 UTC, callumbirks commented
First issue: Unsure whether CBL3.1 included milliseconds by default or not. I thought it didn't, so I removed milliseconds from the default format (found at `DateFormat::kISO8601`). However, this has broken some Fleece tests that don't expect to lose the milliseconds precision.

2024-03-12 23:35 UTC, borrrden commented
Are there tests for this somewhere?  Could they be added to the Fleece tests?

Also I'm kind of unsure if this qualifies as feature creep or not since this is getting out of the scope of a binary encoding.  @snej Do you have an opinion on this?  This functionality needs to be somewhere accessible to Fleece obviously but is it ok to live next to fleece itself?

2024-03-13 14:21 UTC, callumbirks commented
I added a couple tests in Core. Probably does need more.

And I'm not sure. Previously we parse date format strings as DateTime, which restricts us severely. For example, we must use no-colon by default in Timezone specifier, but using DateTime as format we can't offer colon delimited Timezone. So as far as the parser goes, I don't see that the scope is any bigger than it already was (although it may have already had scope creep). However, the %-format is not strictly necessary (although much nicer).

2024-03-13 22:43 UTC, borrrden commented
Can those Core tests be moved here in some fashion and use the underlying classes directly?

2024-03-15 12:10 UTC, callumbirks commented
That would be a good idea... Having to run a Core PR pointing here to make sure nothing's broken over here isn't the best way to write software....

2024-03-19 13:39 UTC, callumbirks commented
@borrrden I've added some DateFormat tests. See `SupportTests.cc`.

2024-03-20 16:20 UTC, snej requested changes
Top-level comment is that this is functionality only needed by CBL N1QL functions, not Fleece itself, so I'd rather the code were put in LiteCore.

2024-03-20 16:20 UTC, snej commented on Fleece/Support/DateFormat.cc
> +            formatString.setStart(formatString.begin() + 2);
`slice_istream` would be pretty useful here, making the code simpler & safer

2024-03-20 16:20 UTC, snej commented on Fleece/Support/DateFormat.hh
> +        struct YMD {
It looks as though the only parts of YMD and HMS that are used by this PR are the separators. I understand wanting room to grow, but all the work of defining types and fields and structs that aren't used yet seems too much ... It seems like each of these structs could be reduced to the Separator enum for now, and it wouldn't be difficult to refactor them back to structs in the future if/when we need it.

2024-03-20 21:53 UTC, borrrden commented
I believe the counterpoint to "this is only used in LiteCore" is "we were using some of this for a specific function in here which writes a datetime to a stream".  In that case at least some of this needs to be accessible here which makes breaking it up somewhat of a pain.

2024-03-20 21:56 UTC, borrrden reviewed
Jens points out some nice feedback so I'll +1 the code parts that he mentioned.

2024-03-21 12:19 UTC, callumbirks commented
Closing. Moved `DateFormat` to Core. See https://github.com/couchbase/couchbase-lite-core/pull/1977

2024-03-21 12:19 UTC, closed without merging

2024-03-21 12:24 UTC, callumbirks commented
@borrrden Regarding
> some of this needs to be accessible here
For now I'm just going along with the duplicated code. Jens said he expected some duplicated code around this, and would rather this not be in Fleece. I definitely agree it doesn't really belong in Fleece, but I think the only solution which doesn't involve duplicated code would be adding a whole new dependency. Which I feel would be more pain than it's worth. It would involve ripping out basically all Date-related functionality from Fleece, and requiring it depend on this dependency.

2024-03-21 12:27 UTC, callumbirks commented on Fleece/Support/DateFormat.hh
> +        DateFormat(YMD ymd, Separator separator, HMS hms, const std::optional<Timezone> tz = {})
But, it is essentially a variable declaration. Which (IMO) should be const if it isn't modified in the function.