CBL-6485 : Define LIFETIMEBOUND only for C++
couchbase/fleece pull request #244
Opened 2024-11-20 23:04 UTC by pasin

* Moved the definition of LIFETIMEBOUND to be next to FLAPI.
* Aligned formatting with the other sections.

2024-11-20 23:19 UTC, snej requested changes
Actually LIFETIMEBOUND should move to PlatformCompat.hh since it's only meant for C++ code.

2024-11-20 23:26 UTC, pasin commented
If moving LIFETIMEBOUND to PlatformCompat.hh, where do we define an empty one for C?

2024-11-21 03:29 UTC, borrrden approved these changes

2024-11-21 17:39 UTC, snej approved these changes

2024-11-21 17:41 UTC, merged